# Generated by Django 4.2.4 on 2023-08-10 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_mynotes_notes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynotes',
            name='notes_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
